### ISSUE TITLE
Create navigation bar

### ISSUE THREAD

**Issue by vivek201102** [developer-student-clubs/resume-builder#1]
### Create Navigation bar
-  Navbar should be same as given sample design
- It should be responsive.

![navbar](https://user-images.githubusercontent.com/69710864/194691352-981bb830-f77e-46a6-844b-176adf8eff47.png)

- You can not change the color palate of the navigation bar
- You can use any style of font.
- Color which have been used
- #444 #000
- At hover on the link color should be #117964
- Responsive design should be as per given image.
![Screenshot 2022-10-08 112651](https://user-images.githubusercontent.com/69710864/194691592-3b3b80f4-6109-4f34-a408-18b7a0a514a2.png)

### Some instructions to follow
- Please create as per given template
- Feel free to contact us for any suggestion.
- Do not ask for pull request unless issue is resolved
- In the case of any query, you can pull request we will try to help into that

-  If you are designing component without using bootstrap that please do not provide class name which are already in use in bootstrap so that there is not conflicts.

**Comment by Nevilkumar** [comment]
Hi @vivek201102 I would like to work on this issue. Can you please assign it to me?

**Comment by jeetsavsani1173** [comment]
Assigned @Nevilkumar     Best Wishes✨

**Comment by harshad125** [comment]
please assigned this issue
