### ISSUE TITLE
add Responsiveness in footer

### ISSUE THREAD

**Issue by jeetsavsani1173** [developer-student-clubs/resume-builder#14]
**add responsiveness in footer such a way looks like good in laptop + tablat + mobial**

**Comment by ishita1805** [comment]
Hi, i'd like to pick this up

**Comment by jeetsavsani1173** [comment]
Assigned @ishita1805 
Best wishes 💫🤞

**Comment by avezqureshi14** [comment]
Bro can you assign this to me

**Comment by jeetsavsani1173** [comment]
Assigned @avezqureshi14 
Best wishes 💫

**Comment by ishita1805** [comment]
Hi My PR is pending a review, lemme know what you think @jeetsavsani1173

**Comment by ishita1805** [comment]
Could you also add the `hacktoberfest-accepted` label to my PR? @jeetsavsani1173
