### ISSUE TITLE
Create a Home Page Component

### ISSUE THREAD

**Issue by jeetsavsani1173** [developer-student-clubs/resume-builder#2]
**Make Home Page component in react for resu.me Builder website**
- add bootstrap container with one image and some text like intro about website like show in blow pic
- add Two button one for SignIn and other for SignUp
- Make responsive component

**like this ➡**
![image](https://user-images.githubusercontent.com/87079541/194694039-23c85ba0-72b9-4cea-9eff-a8d31fabbc12.png)

**for more information you can refer this website** -- > [https://novoresume.com/page/o/auth-required?pageAuthDesired=/editor](url)

- If you are designing component without using bootstrap that please do not provide class name which are already in use in bootstrap so that there is not conflicts.

**Best Wishes**🎈

**Comment by Chaitanya-087** [comment]
i would like to work on this issue

**Comment by jeetsavsani1173** [comment]
I have Assigned @Chaitanya-087 <br> Now You can work on this issue.. you can give star to this repo <br> best Wishes🎉

**Comment by Chaitanya-087** [comment]
ok

**Comment by Chaitanya-087** [comment]
where do i get that image

**Comment by jeetsavsani1173** [comment]
@Chaitanya-087 you are free to put any related image
