### ISSUE TITLE
Create a Footer component

### ISSUE THREAD

**Issue by jeetsavsani1173** [developer-student-clubs/resume-builder#5]
**Make Footer component in react for resu.me Builder website**
- add Button of Social App Like Facebook,linkedin,twitter,instagram
- add for vertical part like show in below picture

**like this ➡**
![image](https://user-images.githubusercontent.com/87079541/195631323-4f782d5d-eee1-4859-88d8-a9a043fca6bc.png)

**for more information you can refer this website** -- > [https://novoresume.com/page/o/auth-required?pageAuthDesired=/editor](url)

- If you are designing component without using bootstrap that please do not provide class name which are already in use in bootstrap so that there is not conflicts.

**Best Wishes**🎈

**Comment by patelyash5208** [comment]
please assign me this issue @jeetsavsani1173

**Comment by jeetsavsani1173** [comment]
Assigned Done @patelyash5208  <br> Best Of Luck(●'◡'●)

**Comment by ashu2206** [comment]
plz assign me

**Comment by jeetsavsani1173** [comment]
@ashu2206 footer is already added <br> You can make more beautifull and responsive if you wish <br> Best Wishes🎇

**Comment by ashu2206** [comment]
okk
