### ISSUE TITLE
Create a SignUp(Register) form

### ISSUE THREAD

**Issue by jeetsavsani1173** [developer-student-clubs/resume-builder#7]
**Make SignUp form component in react for resu.me Builder website**
- when user clicked on SignUp button this component should be render
- add bootstrap container with left side one image and right side some text and input field like Name and Email
- add  one button for Register Now
- Make responsive component
- you can Avoid field called SignIn with Google for Now..

**like this ➡**
![image](https://user-images.githubusercontent.com/87079541/196222039-741c1b20-6b3f-425f-8ab1-029cfeb59941.png)

**for more information you can refer this website** -- > [https://novoresume.com/page/o/auth-required?pageAuthDesired=/editor](url)

- If you are designing component without using bootstrap that please do not provide class name which are already in use in bootstrap so that there is not conflicts.

**Best Wishes**🎈

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by Gulshan-11** [comment]
Hey @jeetsavsani1173 I can work on this too.

**Comment by jeetsavsani1173** [comment]
Assigned @20RitikSingh and @Gulshan-11   <br> Best Wishes✨🎉 <br> Give star to repo if you like (●'◡'●) <br> Thank You..

**Comment by jaswindersingh2601** [comment]
Hey @jeetsavsani1173, I want to work on this issue.

**Comment by jeetsavsani1173** [comment]
Assigned @jaswindersingh2601  <br> Best Wishes✨🎉 <br> Give star to repo if you like (●'◡'●)

**Comment by Gulshan-11** [comment]
Could you please share the image here

**Comment by jeetsavsani1173** [comment]
@Gulshan-11 I have already shared in description
Are you talking about any other images ??

**Comment by Gulshan-11** [comment]
hey can you close this issue 
closes #9
