### ISSUE TITLE
Create a SignIn form

### ISSUE THREAD

**Issue by jeetsavsani1173** [developer-student-clubs/resume-builder#8]
**Make SignIn form component in react for resu.me Builder website**
- when user clicked on SignIn button this component should be render
- add bootstrap container with left side one image and right side some text and input field like Email and password
- add  one button for signIn
- Make responsive component

**like this ➡**
![image](https://user-images.githubusercontent.com/87079541/196223638-11857ffa-9685-4e72-a5c7-ee49f9083d30.png)

**for more information you can refer this website** -- > [https://novoresume.com/page/o/auth-required?pageAuthDesired=/editor](url)

- If you are designing component without using bootstrap that please do not provide class name which are already in use in bootstrap so that there is not conflicts.

**Best Wishes**🎈

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by jeetsavsani1173** [comment]
Assigned @20RitikSingh  <br> Best Wishes✨🎉 <br> Give star to repo if you like (●'◡'●)

**Comment by Gulshan-11** [comment]
assign it to me i will do it

**Comment by jeetsavsani1173** [comment]
Assigned @Gulshan-11

**Comment by Gulshan-11** [comment]
Hey @jeetsavsani1173 Look this out

**Comment by Gulshan-11** [comment]
Hey @jeetsavsani1173 Please merge it as soon as possible
